# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuG3CEbVJKhoD8yGZBKIsgHbJoO7_Kav

1 - Faça um programa para adivinhar um número de 0 a 10000. Se você errar o computador deverá responder se é mais ou menos. Se você errar 10 vezes você perde o jogo.
"""

import random

def adivinhar_numero():
    # Número aleatório gerado pelo computador entre 0 e 10000
    numero_secreto = random.randint(0, 10000)
    tentativas = 0
    max_tentativas = 10

    print("Bem-vindo ao jogo de adivinhar o número!")
    print("Eu escolhi um número entre 0 e 10000. Tente adivinhar.")

    while tentativas < max_tentativas:
        # Solicita o palpite do usuário
        palpite = int(input(f"Tentativa {tentativas + 1}/{max_tentativas}: Qual o seu palpite? "))

        # Verifica se o palpite está correto
        if palpite == numero_secreto:
            print(f"Parabéns! Você adivinhou o número {numero_secreto}.")
            break
        elif palpite < numero_secreto:
            print("O número secreto é maior.")
        else:
            print("O número secreto é menor.")

        tentativas += 1

    if tentativas == max_tentativas:
        print(f"Você perdeu! O número secreto era {numero_secreto}.")

# Inicia o jogo
adivinhar_numero()