# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTOryBDCmPUVKg4z1s8dyUZoCtbtM0-D
"""

# Faça um programa de um caixa eletrônico que, a partir do valor a ser sacado informado pelo usuário,
# o programa informe a menor quantidade de células que o usuário irá receber, informando-o quantas cédulas
# e de quais valores ele irá rceber. Considerar apenas notas: R$: 200, 100, 50, 20, 10, 5, 2
# Exemplo: R$ 858 o prgrama irá informar:
# Cédulas de 200: 4, de 50: 1, de 5: 1, 2: 1

from os import system
system('cls')

#lista com os valores das cédulas disponíveis
def caixa_eletronico(valor):
  cedulas = [200, 100, 50, 20, 10, 5, 2]
  resultado = {} # dicionário para armazenar a quantidade de cédulas de cada valor

#calcula a quantdade de cédulas para cada valor
  for cedula in cedulas:
      if valor >= cedula:
        quantidade = valor // cedula #quantidade de cédulas do valor atual

#quantas cedulas desse valor
        valor %= cedula #atualiza o valor restante a ser sacado
        resultado[cedula] = quantidade

#exibe o resultado
  print("Você receberá as notas:")
  for cedula, quantidade in resultado.items():
      print(f"Cédulas de {cedula} reais: {quantidade}")

#entrada do valor a ser sacado
try:
  valor_saque = int(input("Digite o valor a ser sacado: R$ "))
  if valor_saque > 0 : caixa_eletronico(valor_saque)
  else:
    print("O valor deve ser maior que zero.")
except ValueError:
  print("Por favor,  insira um número inteiro válido.")