# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTOryBDCmPUVKg4z1s8dyUZoCtbtM0-D
"""

# Forca Finalizada

# Palavra secreta
secreta = 'banana'

# Número de tentativas
tentativas = 6

# Estado inicial da palavra oculta
estado = '-' * len(secreta)

# Loop de tentativas
for tentativa in range(tentativas):
    # Exibe o estado atual da palavra
    print(f"Palavra da Forca: {estado}")
    letra = input('Digite uma letra: ').lower()

    # Verifica se a letra está na palavra secreta
    novo_estado = ''
    for i in range(len(secreta)):
        if secreta[i] == letra:
            novo_estado += letra  # A letra correta é revelada
        else:
            novo_estado += estado[i]  # Mantém as letras já adivinhadas

    # Atualiza o estado da palavra
    estado = novo_estado

    # Verifica se a palavra foi totalmente adivinhada
    if '-' not in estado:
        print(f"Parabéns! Você adivinhou a palavra: {estado}")
        break
    else:
        print(f"Estado atual: {estado}")

# Se o número de tentativas acabar
if '-' in estado:
    print(f"Você perdeu! A palavra secreta era: {secreta}")

# FORCA

secreta = 'banana'

for i in range(5):
  letra = input('digite uma letra: ')

  resultado = ''
  for i in secreta:
    if letra == i:
      resultado += i
    else:
      resultado += '-'
  print(resultado)