# -*- coding: utf-8 -*-
"""grafico_haddop_seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpLLmeed2LTy1zC0I7NqXkMKPZIdNnOc
"""

from google.colab import files


uploaded = files.upload()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('employee.csv')
df

grau_education = df.groupby(['employee.education_level', 'employee.position_id', 'employee.gender'])['employee.marital_status'].agg(pd.Series.mode).reset_index().sort_values('employee.position_id', ascending=True)  # Adiciona marital_status no agrupamento
grau_education.columns = ['Grau de Educação', 'id', 'Gênero', '(Single/Married)']
grau_education.drop(columns=['id'], inplace=True)
grau_education = grau_education.head(1000)
grau_education

#contagem
plt.figure(figsize=(10, 6))
sns.countplot(data=grau_education, x='Grau de Educação', hue='Gênero', palette='Set2')

#personalizando o gráfico
plt.title('Relação Grau de Educação e Gênero', fontsize=16)
plt.xlabel('Grau de Educação', fontsize=14)
plt.ylabel('Status de Relacionamento', fontsize=14)
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()