# -*- coding: utf-8 -*-
"""Haddop_seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zq_SSt-XZtel_cG8OhOhNhMv9brr1Izc
"""

from google.colab import files


uploaded = files.upload()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.set(style="whitegrid")
plt.figure(figsize=(8, 6))

# Alteração: Usando colunas 'total_bill' e 'tip'
sns.scatterplot(data=tips, x="total_bill", y="tip", hue="sex", style="time", palette="coolwarm")

plt.title("Relação entre Salários e Características do Funcionário")
plt.xlabel("Característica do Funcionário")
plt.ylabel("Salário")
plt.show()

['employee.salary', 'employee.supervisor', 'employee.education_level', 'employee.marital_status']

sns.relplot(x='employee.salary', y='employee.education_level', data=usd, kind='line', height=6, aspect=4)