# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjDf39sjW30npEG2Z4jbE3CQvurp1snj

Lista de exercícios 3

2- Faça um programa para avaliar qual o número que mais cai em um lance de dados (D6). O sistema deverá lançar um conjunto de dois dados n vezes seguidas, onde n é o número de vezes que você informar ao computador.
Após jogar os dados, o sistema deverá informar quantas vezes a soma deu um dos números possíveis: 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 e 12  🎲
"""

import random

def contar_somas_lancamentos(n):
    # Inicializa um dicionário para contar a quantidade de cada soma possível (de 2 a 12)
    contagem = {i: 0 for i in range(2, 13)}

    for _ in range(n):
        # Simula o lançamento de dois dados D6
        dado1 = random.randint(1, 6)
        dado2 = random.randint(1, 6)

        # Soma os resultados dos dois dados
        soma = dado1 + dado2

        # Incrementa a contagem da soma obtida
        contagem[soma] += 1

    # Exibe a quantidade de vezes que cada soma ocorreu
    for soma in range(2, 13):
        print(f"Soma {soma}: {contagem[soma]} vezes")

# Solicita o número de lançamentos ao usuário
n = int(input("Digite o número de vezes que os dados serão lançados: "))

# Chama a função para realizar os lançamentos e contar as somas
contar_somas_lancamentos(n)