# -*- coding: utf-8 -*-
"""Matplotlib_kart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSWKJy8YTGAbwwOS0U7FNTJ8N5GmEqHb
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dados = np.random.uniform(6, 10, size=(6, 10))

df1 = pd.DataFrame(dados,index=['Senna', 'Massa', 'Barrichello', 'Schummacker', 'Hamilton', 'Takumasato'], columns=['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10'])

print('O campeão foi ',df1.sum(axis = 1).idxmin(), ' que fez ', df1.sum(axis = 1).min(), ' segundos!!!' )
df1

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dados = np.random.uniform(6, 10, size=(6, 10))
df1 = pd.DataFrame(dados, index=['Senna', 'Massa', 'Barrichello', 'Schummacker', 'Hamilton', 'Takumasato'], columns=['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10'])
print('O campeão foi ',df1.sum(axis = 1).idxmin(), ' que fez ', df1.sum(axis = 1).min(), ' segundos!!!' )
df1

#calculando os tempos totais e ordenação
tempos_totais = df1.sum(axis=1).sort_values(ascending=False)

#criando o gráfico com barras horizontais com matplotlib
plt.figure(figsize=(12, 8))
plt.barh(tempos_totais.index, tempos_totais, color='cornflowerblue', edgecolor='black')

#editando a aparência e perfumaria do gráfico
plt.title('Tempo Total por Piloto', fontsize=18, fontweight='bold')
plt.xlabel('Tempo Total (segundos)', fontsize=14)
plt.ylabel('Posição dos Pilotos', fontsize=14)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.gca().invert_yaxis()  # Inverter a ordem para o maior valor no topo

#adicionando os valores ao lado das barras
for i, v in enumerate(tempos_totais):
    plt.text(v + 0.1, i, f'{v:.2f}', va='center', fontsize=12)

#show exibe o gráfico
plt.tight_layout()
plt.show()