# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4Qorb7QeaJyqfIb_gE7I94iMrKhO_MO

Lista 4

1- Crie uma função que receba um nome, separe as 4 primeiras letras e complete com a palavra mon.
Ex: **Dani**el -> **Danimon**
"""

def completar_nome(nome):
    # Pega as 4 primeiras letras do nome e adiciona "mon"
    novo_nome = nome[:4] + "mon"
    return novo_nome

# Solicita o nome ao usuário
nome_usuario = input("Digite o seu nome: ")

# Chama a função para completar o nome
resultado = completar_nome(nome_usuario)

# Exibe o resultado
print(f"O nome modificado é: {resultado}")