# -*- coding: utf-8 -*-
"""NumpyCorrida.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o65n02fhGwMx4uJ37Actz2cDvzjUZ-OU
"""

import numpy as np

# número de corredores e voltas
num_corredores = 6
num_voltas = 10

# matriz com os tempos aleatórios
tempos = np.random.uniform(1, 10, (num_corredores, num_voltas))
print(tempos)

# Melhor volta da prova (menor tempo)
melhor_tempo = np.min(tempos)
melhor_corredor, melhor_volta = np.unravel_index(np.argmin(tempos), tempos.shape)

# Classificação final por tempo total (soma dos tempos de todas as voltas)
tempo_total = np.sum(tempos, axis=1)
classificacao = np.argsort(tempo_total)

# Volta com a média mais rápida (menor média de tempo)
media_volta = np.mean(tempos, axis=0)
volta_rapida = np.argmin(media_volta)

# Exibindo os resultados
print(f"Melhor volta: Corredor {melhor_corredor+1}, Volta {melhor_volta+1}, Tempo: {melhor_tempo:.2f} segundos.")
print("\nClassificação final (em ordem crescente de tempo total):")
for i, corredor in enumerate(classificacao, 1):
    print(f"{i}. Corredor {corredor+1} - Tempo Total: {tempo_total[corredor]:.2f} segundos")

print(f"\nVolta com a média mais rápida: Volta {volta_rapida+1}, Tempo médio: {media_volta[volta_rapida]:.2f} segundos.")