# -*- coding: utf-8 -*-
"""PySpark_Kart1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfFd81QQQqehqVAfTO7XMSUSFWoSBdWm
"""

pip install pyspark

from pyspark.sql import SparkSession
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Inicializando a SparkSession
spark = SparkSession.builder.master("local").appName("Pilotos").getOrCreate()

# Gerando dados aleatórios com numpy
dados = np.random.uniform(6, 10, size=(6, 10))

# Criando um DataFrame do PySpark
pilotos = ['Senna', 'Massa', 'Barrichello', 'Schummacker', 'Hamilton', 'Takumasato']
colunas = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10']

# Criando um DataFrame pandas temporário para usar com PySpark
df_pandas = pd.DataFrame(dados, index=pilotos, columns=colunas)

# Convertendo para PySpark DataFrame
df_spark = spark.createDataFrame(df_pandas)

# Exibindo o DataFrame PySpark
df_spark.show()

# Calculando a soma dos tempos por piloto
from pyspark.sql.functions import col, sum as spark_sum

# Adicionando uma coluna com a soma dos tempos para cada piloto
df_spark_with_sum = df_spark.withColumn("total_time", sum(col(c) for c in colunas))

# Coletando o resultado para o pandas
result = df_spark_with_sum.select("total_time").toPandas()

# Encontrando o campeão (piloto com o menor tempo total)
total_time = result['total_time']
champion = total_time.idxmin()
min_time = total_time.min()

print(f'O campeão foi {champion} que fez {min_time} segundos!!!')

# Criando um gráfico de barras
plt.figure(figsize=(12, 8))
sns.barplot(
    x=total_time.sort_values(ascending=False),
    y=total_time.sort_values(ascending=False).index,
    palette='coolwarm',
    orient='h'
)

plt.title('Tempo Total por Piloto', fontsize=16, fontweight='bold')
plt.xlabel('Tempo Total (segundos)', fontsize=14)
plt.ylabel('Pilotos', fontsize=14)

# Exibir o gráfico
plt.show()