# -*- coding: utf-8 -*-
"""Seaborn_kart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9Oe9N_S1PTp_lmuY1QCOoXvhEgl1vEj
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dados = np.random.uniform(6, 10, size=(6, 10))

df1 = pd.DataFrame(dados,index=['Senna', 'Massa', 'Barrichello', 'Schummacker', 'Hamilton', 'Takumasato'], columns=['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10'])

print('O campeão foi ',df1.sum(axis = 1).idxmin(), ' que fez ', df1.sum(axis = 1).min(), ' segundos!!!' )
df1

# criando um gráfico
plt.figure(figsize=(12, 8))
sns.barplot(
    x=df1.sum(axis=1).sort_values(ascending=False),
    y=df1.sum(axis=1).sort_values(ascending=False).index,
    palette='coolwarm',
    orient='h'
)

plt.title('Tempo Total por Piloto', fontsize=16, fontweight='bold')
plt.xlabel('Tempo Total (segundos)', fontsize=14)
plt.ylabel('Pilotos', fontsize=14)

# Exibir o gráfico
plt.show()