# -*- coding: utf-8 -*-
"""Spark_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD0WnzUPxdN5cHrTzns_fgfQKrhyE-yT
"""

from google.colab import files


uploaded = files.upload()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('Hadoop_Fernando.csv.csv')