# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHsAkxhBbmSh34idu_5L69jIZ0wLv8Gq
"""

if idade >= 0 and idade < 16:
  print('Você não pode apenas votar')

elif idade >= 16 and idade < 18:
  print('Você pode apenas votar')

elif idade >=18 and idade < 21:
  print('Você pod votar e tem maioridade penal')

elif idade >= 21 and idade < 120:
  print('Você pode votar, tem maioridade penal e civil')

else:
  print('Idade errada')